import type { Metadata, Viewport } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import { ChatStoreProvider } from '@/providers/chat-store-provider'
import { InteractionStoreProvider } from '@/providers/interaction-store-provider'
import { MenuDrawer } from './components/common/MenuDrawer'
import { MenuDrawerProvider } from '@/providers/menu-drawer.provider'
import { ThemeProvider } from '@/providers/theme.provider'
import { TtsStoreProvider } from '@/providers/tts-store-provider'
import './globals.scss'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const viewport: Viewport = {
  initialScale: 1,
  minimumScale: 1,
  maximumScale: 1,
  width: 'device-width',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} overflow-hidden antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark" forcedTheme="dark">
          <TtsStoreProvider>
            <ChatStoreProvider>
              <InteractionStoreProvider>
                <MenuDrawerProvider>
                  <div className="flex items-center justify-center">
                    {children}
                  </div>

                  <MenuDrawer />
                </MenuDrawerProvider>
              </InteractionStoreProvider>
            </ChatStoreProvider>
          </TtsStoreProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
