import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
<<<<<<< HEAD
import "./globals.scss";

import { ChatStoreProvider } from "@/providers/chat-store-provider";
import { InteractionStoreProvider } from "@/providers/interaction-store-provider";
=======
import "./globals.css";
import { ChatStoreProvider } from "@/providers/chat-store-provider";
>>>>>>> 29417e0 (feat: :sparkles: Initial commit)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
        <ChatStoreProvider>
          <InteractionStoreProvider>{children}</InteractionStoreProvider>
        </ChatStoreProvider>
=======
        <ChatStoreProvider>{children}</ChatStoreProvider>
>>>>>>> 29417e0 (feat: :sparkles: Initial commit)
      </body>
    </html>
  );
}
